<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Seeders
|--------------------------------------------------------------------------
|
| Seders are used to generate datas to populate the database of the test environment.
|
*/

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
          array('id' => '1','name' => 'Italy','continent_id' => '6','code' => 'IT'),
          array('id' => '2','name' => 'United States','continent_id' => '3','code' => 'US'),
          array('id' => '3','name' => 'Algeria','continent_id' => '1','code' => 'DZ'),
          array('id' => '4','name' => 'Wallis and Futuna','continent_id' => '4','code' => 'WF'),
          array('id' => '5','name' => 'Angola','continent_id' => '1','code' => 'AO'),
          array('id' => '6','name' => 'Benin','continent_id' => '1','code' => 'BJ'),
          array('id' => '7','name' => 'Botswana','continent_id' => '1','code' => 'BW'),
          array('id' => '8','name' => 'Burkina Faso','continent_id' => '1','code' => 'BF'),
          array('id' => '9','name' => 'Burundi','continent_id' => '1','code' => 'BI'),
          array('id' => '10','name' => 'Cameroon','continent_id' => '1','code' => 'CM'),
          array('id' => '11','name' => 'Cape Verde','continent_id' => '1','code' => 'CV'),
          array('id' => '12','name' => 'Central African Republic','continent_id' => '1','code' => 'CF'),
          array('id' => '13','name' => 'Chad','continent_id' => '1','code' => 'TD'),
          array('id' => '14','name' => 'Comoros','continent_id' => '1','code' => 'KM'),
          array('id' => '15','name' => 'Congo - Brazzaville','continent_id' => '1','code' => 'CG'),
          array('id' => '16','name' => 'Congo - Kinshasa','continent_id' => '1','code' => 'CD'),
          array('id' => '17','name' => 'Cote d\'Ivoire','continent_id' => '1','code' => 'CI'),
          array('id' => '18','name' => 'Djibouti','continent_id' => '1','code' => 'DJ'),
          array('id' => '19','name' => 'Egypt','continent_id' => '1','code' => 'EG'),
          array('id' => '20','name' => 'Equatorial Guinea','continent_id' => '1','code' => 'GQ'),
          array('id' => '21','name' => 'Eritrea','continent_id' => '1','code' => 'ER'),
          array('id' => '22','name' => 'Ethiopia','continent_id' => '1','code' => 'ET'),
          array('id' => '23','name' => 'Gabon','continent_id' => '1','code' => 'GA'),
          array('id' => '24','name' => 'Gambia','continent_id' => '1','code' => 'GM'),
          array('id' => '25','name' => 'Ghana','continent_id' => '1','code' => 'GH'),
          array('id' => '26','name' => 'Guinea','continent_id' => '1','code' => 'GN'),
          array('id' => '27','name' => 'Guinea Bissau','continent_id' => '1','code' => 'GW'),
          array('id' => '28','name' => 'Kenya','continent_id' => '1','code' => 'KE'),
          array('id' => '29','name' => 'Lesotho','continent_id' => '1','code' => 'LS'),
          array('id' => '30','name' => 'Liberia','continent_id' => '1','code' => 'LR'),
          array('id' => '31','name' => 'Libya','continent_id' => '1','code' => 'LY'),
          array('id' => '32','name' => 'Madagascar','continent_id' => '1','code' => 'MG'),
          array('id' => '33','name' => 'Malawi','continent_id' => '1','code' => 'MW'),
          array('id' => '34','name' => 'Mali','continent_id' => '1','code' => 'ML'),
          array('id' => '35','name' => 'Mauritania','continent_id' => '1','code' => 'MR'),
          array('id' => '36','name' => 'Mauritius','continent_id' => '1','code' => 'MU'),
          array('id' => '37','name' => 'Mayotte','continent_id' => '1','code' => 'YT'),
          array('id' => '38','name' => 'Morocco','continent_id' => '1','code' => 'MA'),
          array('id' => '39','name' => 'Mozambique','continent_id' => '1','code' => 'MZ'),
          array('id' => '40','name' => 'Namibia','continent_id' => '1','code' => 'NA'),
          array('id' => '41','name' => 'Niger','continent_id' => '1','code' => 'NE'),
          array('id' => '42','name' => 'Vanuatu','continent_id' => '4','code' => 'VU'),
          array('id' => '43','name' => 'Rwanda','continent_id' => '1','code' => 'RW'),
          array('id' => '44','name' => 'Reunion','continent_id' => '1','code' => 'RE'),
          array('id' => '45','name' => 'Saint Helena','continent_id' => '1','code' => 'SH'),
          array('id' => '46','name' => 'Senegal','continent_id' => '1','code' => 'SN'),
          array('id' => '47','name' => 'Seychelles','continent_id' => '1','code' => 'SC'),
          array('id' => '48','name' => 'Sierra Leone','continent_id' => '1','code' => 'SL'),
          array('id' => '49','name' => 'Somalia','continent_id' => '1','code' => 'SO'),
          array('id' => '50','name' => 'South Africa','continent_id' => '1','code' => 'ZA'),
          array('id' => '51','name' => 'Sudan','continent_id' => '1','code' => 'SD'),
          array('id' => '52','name' => 'Swaziland','continent_id' => '1','code' => 'SZ'),
          array('id' => '53','name' => 'Sao Tome and Príncipe','continent_id' => '1','code' => 'ST'),
          array('id' => '54','name' => 'Tanzania','continent_id' => '1','code' => 'TZ'),
          array('id' => '55','name' => 'Togo','continent_id' => '1','code' => 'TG'),
          array('id' => '56','name' => 'Tunisia','continent_id' => '1','code' => 'TN'),
          array('id' => '57','name' => 'Uganda','continent_id' => '1','code' => 'UG'),
          array('id' => '58','name' => 'U.S. Minor Outlying Islands','continent_id' => '4','code' => 'UM'),
          array('id' => '59','name' => 'Tuvalu','continent_id' => '4','code' => 'TV'),
          array('id' => '60','name' => 'Western Sahara','continent_id' => '1','code' => 'EH'),
          array('id' => '61','name' => 'Zambia','continent_id' => '1','code' => 'ZM'),
          array('id' => '62','name' => 'Zimbabwe','continent_id' => '1','code' => 'ZW'),
          array('id' => '63','name' => 'Anguilla','continent_id' => '3','code' => 'AI'),
          array('id' => '64','name' => 'Antigua and Barbuda','continent_id' => '3','code' => 'AG'),
          array('id' => '65','name' => 'Argentina','continent_id' => '7','code' => 'AR'),
          array('id' => '66','name' => 'Aruba','continent_id' => '7','code' => 'AW'),
          array('id' => '67','name' => 'Bahamas','continent_id' => '3','code' => 'BS'),
          array('id' => '68','name' => 'Barbados','continent_id' => '7','code' => 'BB'),
          array('id' => '69','name' => 'Belize','continent_id' => '3','code' => 'BZ'),
          array('id' => '70','name' => 'Bermuda','continent_id' => '3','code' => 'BM'),
          array('id' => '71','name' => 'Bolivia','continent_id' => '7','code' => 'BO'),
          array('id' => '72','name' => 'Brazil','continent_id' => '7','code' => 'BR'),
          array('id' => '73','name' => 'British Virgin Islands','continent_id' => '3','code' => 'VG'),
          array('id' => '74','name' => 'Canada','continent_id' => '3','code' => 'CA'),
          array('id' => '75','name' => 'Cayman Islands','continent_id' => '3','code' => 'KY'),
          array('id' => '76','name' => 'Chile','continent_id' => '7','code' => 'CL'),
          array('id' => '77','name' => 'Colombia','continent_id' => '7','code' => 'CO'),
          array('id' => '78','name' => 'Costa Rica','continent_id' => '3','code' => 'CR'),
          array('id' => '79','name' => 'Cuba','continent_id' => '3','code' => 'CU'),
          array('id' => '80','name' => 'Dominica','continent_id' => '3','code' => 'DM'),
          array('id' => '81','name' => 'Dominican Republic','continent_id' => '3','code' => 'DO'),
          array('id' => '82','name' => 'Ecuador','continent_id' => '7','code' => 'EC'),
          array('id' => '83','name' => 'El Salvador','continent_id' => '3','code' => 'SV'),
          array('id' => '84','name' => 'Falkland Islands','continent_id' => '7','code' => 'FK'),
          array('id' => '85','name' => 'French Guiana','continent_id' => '7','code' => 'GF'),
          array('id' => '86','name' => 'Greenland','continent_id' => '3','code' => 'GL'),
          array('id' => '87','name' => 'Grenada','continent_id' => '3','code' => 'GD'),
          array('id' => '88','name' => 'Guadeloupe','continent_id' => '3','code' => 'GP'),
          array('id' => '89','name' => 'Guatemala','continent_id' => '3','code' => 'GT'),
          array('id' => '90','name' => 'Guyana','continent_id' => '7','code' => 'GY'),
          array('id' => '91','name' => 'Haiti','continent_id' => '3','code' => 'HT'),
          array('id' => '92','name' => 'Honduras','continent_id' => '3','code' => 'HN'),
          array('id' => '93','name' => 'Jamaica','continent_id' => '3','code' => 'JM'),
          array('id' => '94','name' => 'Martinique','continent_id' => '3','code' => 'MQ'),
          array('id' => '95','name' => 'Mexico','continent_id' => '7','code' => 'MX'),
          array('id' => '96','name' => 'Montserrat','continent_id' => '3','code' => 'MS'),
          array('id' => '97','name' => 'Netherlands Antilles','continent_id' => '7','code' => 'AN'),
          array('id' => '98','name' => 'Nicaragua','continent_id' => '3','code' => 'NI'),
          array('id' => '99','name' => 'Panama','continent_id' => '3','code' => 'PA'),
          array('id' => '100','name' => 'Paraguay','continent_id' => '7','code' => 'PY'),
          array('id' => '101','name' => 'Peru','continent_id' => '7','code' => 'PE'),
          array('id' => '102','name' => 'Puerto Rico','continent_id' => '3','code' => 'PR'),
          array('id' => '103','name' => 'Saint Barthelemy','continent_id' => '3','code' => 'BL'),
          array('id' => '104','name' => 'Saint Kitts and Nevis','continent_id' => '3','code' => 'KL'),
          array('id' => '105','name' => 'Saint Lucia','continent_id' => '3','code' => 'LC'),
          array('id' => '106','name' => 'Saint Martin','continent_id' => '3','code' => 'MF'),
          array('id' => '107','name' => 'Saint Pierre and Miquelon','continent_id' => '3','code' => 'PM'),
          array('id' => '108','name' => 'Saint Vincent and the Grenadines','continent_id' => '3','code' => 'VC'),
          array('id' => '109','name' => 'Suriname','continent_id' => '7','code' => 'SR'),
          array('id' => '110','name' => 'Trinidad and Tobago','continent_id' => '7','code' => 'TT'),
          array('id' => '111','name' => 'Turks and Caicos Islands','continent_id' => '3','code' => 'TC'),
          array('id' => '112','name' => 'U.S. Virgin Islands','continent_id' => '3','code' => 'VI'),
          array('id' => '113','name' => 'Tonga','continent_id' => '4','code' => 'TO'),
          array('id' => '114','name' => 'Uruguay','continent_id' => '7','code' => 'UY'),
          array('id' => '115','name' => 'Venezuela','continent_id' => '7','code' => 'VE'),
          array('id' => '116','name' => 'Tokelau','continent_id' => '4','code' => 'TK'),
          array('id' => '117','name' => 'Afghanistan','continent_id' => '5','code' => 'AF'),
          array('id' => '118','name' => 'Armenia','continent_id' => '5','code' => 'AM'),
          array('id' => '119','name' => 'Azerbaijan','continent_id' => '5','code' => 'AZ'),
          array('id' => '120','name' => 'Bahrain','continent_id' => '5','code' => 'BH'),
          array('id' => '121','name' => 'Bangladesh','continent_id' => '5','code' => 'BD'),
          array('id' => '122','name' => 'Bhutan','continent_id' => '5','code' => 'BT'),
          array('id' => '123','name' => 'Brunei','continent_id' => '5','code' => 'BN'),
          array('id' => '124','name' => 'Cambodia','continent_id' => '5','code' => 'KH'),
          array('id' => '125','name' => 'China','continent_id' => '5','code' => 'CN'),
          array('id' => '126','name' => 'Cyprus','continent_id' => '5','code' => 'CY'),
          array('id' => '127','name' => 'Georgia','continent_id' => '5','code' => 'GE'),
          array('id' => '129','name' => 'Hong Kong SAR China','continent_id' => '5','code' => 'HK'),
          array('id' => '130','name' => 'India','continent_id' => '5','code' => 'IN'),
          array('id' => '131','name' => 'Indonesia','continent_id' => '5','code' => 'ID'),
          array('id' => '132','name' => 'Iran','continent_id' => '5','code' => 'IR'),
          array('id' => '133','name' => 'Iraq','continent_id' => '5','code' => 'IQ'),
          array('id' => '134','name' => 'Israel','continent_id' => '5','code' => 'IL'),
          array('id' => '135','name' => 'Japan','continent_id' => '5','code' => 'JP'),
          array('id' => '136','name' => 'Jordan','continent_id' => '5','code' => 'JO'),
          array('id' => '137','name' => 'Kazakhstan','continent_id' => '5','code' => 'KZ'),
          array('id' => '138','name' => 'Kuwait','continent_id' => '5','code' => 'KW'),
          array('id' => '139','name' => 'Kyrgyzstan','continent_id' => '5','code' => 'KG'),
          array('id' => '140','name' => 'Laos','continent_id' => '5','code' => 'LA'),
          array('id' => '141','name' => 'Lebanon','continent_id' => '5','code' => 'LB'),
          array('id' => '142','name' => 'Macau SAR China','continent_id' => '5','code' => 'MO'),
          array('id' => '143','name' => 'Malaysia','continent_id' => '5','code' => 'MY'),
          array('id' => '144','name' => 'Maldives','continent_id' => '5','code' => 'MV'),
          array('id' => '145','name' => 'Mongolia','continent_id' => '5','code' => 'MN'),
          array('id' => '146','name' => 'Myanmar Burma','continent_id' => '5','code' => 'MM'),
          array('id' => '147','name' => 'Nepal','continent_id' => '5','code' => 'NP'),
          array('id' => '148','name' => 'Neutral Zone','continent_id' => '5','code' => 'NT'),
          array('id' => '149','name' => 'North Korea','continent_id' => '5','code' => 'KP'),
          array('id' => '150','name' => 'Oman','continent_id' => '5','code' => 'OM'),
          array('id' => '151','name' => 'Pakistan','continent_id' => '5','code' => 'PK'),
          array('id' => '152','name' => 'Palestinian Territories','continent_id' => '5','code' => 'PS'),
          array('id' => '153','name' => 'People s Democratic Republic of Yemen','continent_id' => '5','code' => 'YD'),
          array('id' => '154','name' => 'Philippines','continent_id' => '5','code' => 'PH'),
          array('id' => '155','name' => 'Qatar','continent_id' => '5','code' => 'QA'),
          array('id' => '156','name' => 'Saudi Arabia','continent_id' => '5','code' => 'SA'),
          array('id' => '157','name' => 'Singapore','continent_id' => '5','code' => 'SG'),
          array('id' => '158','name' => 'South Korea','continent_id' => '5','code' => 'KR'),
          array('id' => '159','name' => 'Sri Lanka','continent_id' => '5','code' => 'LK'),
          array('id' => '160','name' => 'Syria','continent_id' => '5','code' => 'SY'),
          array('id' => '161','name' => 'Taiwan','continent_id' => '5','code' => 'TW'),
          array('id' => '162','name' => 'Tajikistan','continent_id' => '5','code' => 'TJ'),
          array('id' => '163','name' => 'Thailand','continent_id' => '5','code' => 'TH'),
          array('id' => '164','name' => 'Timor Leste','continent_id' => '5','code' => 'TL'),
          array('id' => '165','name' => 'Turkey','continent_id' => '5','code' => 'TR'),
          array('id' => '166','name' => 'Turkmenistan','continent_id' => '5','code' => 'TM'),
          array('id' => '167','name' => 'United Arab Emirates','continent_id' => '5','code' => 'AE'),
          array('id' => '168','name' => 'Uzbekistan','continent_id' => '5','code' => 'UZ'),
          array('id' => '169','name' => 'Vietnam','continent_id' => '5','code' => 'VN'),
          array('id' => '170','name' => 'Yemen','continent_id' => '5','code' => 'YE'),
          array('id' => '171','name' => 'Albania','continent_id' => '6','code' => 'AL'),
          array('id' => '172','name' => 'Andorra','continent_id' => '6','code' => 'AD'),
          array('id' => '173','name' => 'Austria','continent_id' => '6','code' => 'AT'),
          array('id' => '174','name' => 'Belarus','continent_id' => '6','code' => 'BY'),
          array('id' => '175','name' => 'Belgium','continent_id' => '6','code' => 'BE'),
          array('id' => '176','name' => 'Bosnia and Herzegovina','continent_id' => '6','code' => 'BA'),
          array('id' => '177','name' => 'Bulgaria','continent_id' => '6','code' => 'BG'),
          array('id' => '178','name' => 'Croatia','continent_id' => '6','code' => 'HR'),
          array('id' => '179','name' => 'South Georgia and the South Sandwich Isl','continent_id' => '4','code' => 'GS'),
          array('id' => '180','name' => 'Czech Republic','continent_id' => '6','code' => 'CZ'),
          array('id' => '181','name' => 'Denmark','continent_id' => '6','code' => 'DK'),
          array('id' => '182','name' => 'Estonia','continent_id' => '6','code' => 'EE'),
          array('id' => '183','name' => 'Faroe Islands','continent_id' => '6','code' => 'FO'),
          array('id' => '184','name' => 'Finland','continent_id' => '6','code' => 'FI'),
          array('id' => '185','name' => 'France','continent_id' => '6','code' => 'FR'),
          array('id' => '186','name' => 'Germany','continent_id' => '6','code' => 'DE'),
          array('id' => '187','name' => 'Gibraltar','continent_id' => '6','code' => 'GI'),
          array('id' => '188','name' => 'Greece','continent_id' => '6','code' => 'GR'),
          array('id' => '189','name' => 'Guernsey','continent_id' => '6','code' => 'GG'),
          array('id' => '190','name' => 'Hungary','continent_id' => '6','code' => 'HU'),
          array('id' => '191','name' => 'Iceland','continent_id' => '6','code' => 'IS'),
          array('id' => '192','name' => 'Ireland','continent_id' => '6','code' => 'IE'),
          array('id' => '193','name' => 'Isle of Man','continent_id' => '6','code' => 'IM'),
          array('id' => '195','name' => 'Jersey','continent_id' => '6','code' => 'JE'),
          array('id' => '196','name' => 'Latvia','continent_id' => '6','code' => 'LV'),
          array('id' => '197','name' => 'Liechtenstein','continent_id' => '6','code' => 'LI'),
          array('id' => '198','name' => 'Lithuania','continent_id' => '6','code' => 'LT'),
          array('id' => '199','name' => 'Luxembourg','continent_id' => '6','code' => 'LU'),
          array('id' => '200','name' => 'Macedonia','continent_id' => '6','code' => 'MK'),
          array('id' => '201','name' => 'Malta','continent_id' => '6','code' => 'MT'),
          array('id' => '202','name' => 'Metropolitan France','continent_id' => '6','code' => 'FX'),
          array('id' => '203','name' => 'Moldova','continent_id' => '6','code' => 'MD'),
          array('id' => '204','name' => 'Monaco','continent_id' => '6','code' => 'MC'),
          array('id' => '205','name' => 'Montenegro','continent_id' => '6','code' => 'ME'),
          array('id' => '206','name' => 'Netherlands','continent_id' => '6','code' => 'NL'),
          array('id' => '207','name' => 'Norway','continent_id' => '6','code' => 'NO'),
          array('id' => '208','name' => 'Poland','continent_id' => '6','code' => 'PL'),
          array('id' => '209','name' => 'Portugal','continent_id' => '6','code' => 'PT'),
          array('id' => '210','name' => 'Romania','continent_id' => '6','code' => 'RO'),
          array('id' => '211','name' => 'Russia','continent_id' => '6','code' => 'RU'),
          array('id' => '212','name' => 'San Marino','continent_id' => '6','code' => 'SM'),
          array('id' => '213','name' => 'Serbia','continent_id' => '6','code' => 'RS'),
          array('id' => '214','name' => 'Serbia and Montenegro','continent_id' => '6','code' => 'CS'),
          array('id' => '215','name' => 'Slovakia','continent_id' => '6','code' => 'SK'),
          array('id' => '216','name' => 'Slovenia','continent_id' => '6','code' => 'SI'),
          array('id' => '217','name' => 'Spain','continent_id' => '6','code' => 'ES'),
          array('id' => '218','name' => 'Svalbard and Jan Mayen','continent_id' => '6','code' => 'SJ'),
          array('id' => '219','name' => 'Sweden','continent_id' => '6','code' => 'SE'),
          array('id' => '220','name' => 'Switzerland','continent_id' => '6','code' => 'CH'),
          array('id' => '221','name' => 'Ukraine','continent_id' => '6','code' => 'UA'),
          array('id' => '222','name' => 'Union of Soviet Socialist Republics','continent_id' => '6','code' => 'SU'),
          array('id' => '223','name' => 'United Kingdom','continent_id' => '6','code' => 'GB'),
          array('id' => '224','name' => 'Vatican City','continent_id' => '6','code' => 'VA'),
          array('id' => '225','name' => 'Aland Islands','continent_id' => '6','code' => 'AX'),
          array('id' => '226','name' => 'American Samoa','continent_id' => '4','code' => 'AS'),
          array('id' => '227','name' => 'Antarctica','continent_id' => '4','code' => 'AQ'),
          array('id' => '228','name' => 'Australia','continent_id' => '4','code' => 'AU'),
          array('id' => '229','name' => 'Bouvet Island','continent_id' => '4','code' => 'BV'),
          array('id' => '230','name' => 'British Indian Ocean Territory','continent_id' => '4','code' => 'IO'),
          array('id' => '231','name' => 'Christmas Island','continent_id' => '4','code' => 'CX'),
          array('id' => '232','name' => 'Cocos Keeling Islands','continent_id' => '4','code' => 'CC'),
          array('id' => '234','name' => 'Cook Islands','continent_id' => '4','code' => 'CK'),
          array('id' => '235','name' => 'Fiji','continent_id' => '4','code' => 'FJ'),
          array('id' => '236','name' => 'French Polynesia','continent_id' => '4','code' => 'PF'),
          array('id' => '237','name' => 'French Southern Territories','continent_id' => '4','code' => 'TF'),
          array('id' => '238','name' => 'Guam','continent_id' => '4','code' => 'GU'),
          array('id' => '239','name' => 'Heard Island and McDonald Islands','continent_id' => '4','code' => 'HM'),
          array('id' => '240','name' => 'Kiribati','continent_id' => '4','code' => 'KI'),
          array('id' => '241','name' => 'Marshall Islands','continent_id' => '4','code' => 'MH'),
          array('id' => '242','name' => 'Micronesia','continent_id' => '4','code' => 'FM'),
          array('id' => '243','name' => 'Nauru','continent_id' => '4','code' => 'NR'),
          array('id' => '244','name' => 'New Caledonia','continent_id' => '4','code' => 'NC'),
          array('id' => '245','name' => 'New Zealand','continent_id' => '4','code' => 'NZ'),
          array('id' => '246','name' => 'Niue','continent_id' => '4','code' => 'NU'),
          array('id' => '247','name' => 'Norfolk Island','continent_id' => '4','code' => 'NF'),
          array('id' => '248','name' => 'Northern Mariana Islands','continent_id' => '4','code' => 'MP'),
          array('id' => '249','name' => 'Palau','continent_id' => '4','code' => 'PW'),
          array('id' => '250','name' => 'Papua New Guinea','continent_id' => '4','code' => 'PG'),
          array('id' => '251','name' => 'Pitcairn Islands','continent_id' => '4','code' => 'PN'),
          array('id' => '252','name' => 'Samoa','continent_id' => '4','code' => 'WS'),
          array('id' => '253','name' => 'Solomon Islands','continent_id' => '4','code' => 'SB')
        );

        //dump($countries);
        foreach($countries as $key => $country) {
            DB::table('countries')->insert([
                'id' => $country['id'],
                'name' => $country['name'],
                'continent_id' => $country['continent_id'],
                'code' => $country['code'],
            ]);
        }
    
    }
}
