<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menuItems = [
            ['id' => '1',
                'name' => 'Home',
                'slug' => 'home',
                'menu_id' => '1',
                'order' => '1',
                'access' => '1',
                'type' => '2',
                'parent_item_id' => '0',
                'url' => '/',
                'route' => '',
                'font_awesome_class' => 'fa fa-home',
                'hide_name' => '0',
            ],
            ['id' => '2',
                'name' => 'Manager',
                'slug' => 'manager',
                'menu_id' => '4',
                'order' => '1',
                'access' => '3',
                'type' => '2',
                'parent_item_id' => '0',
                'url' => '#',
                'route' => '',
                'font_awesome_class' => 'fa fas fa-edit',
                'hide_name' => '0',
            ],
            ['id' => '3',
                'name' => 'New Event',
                'slug' => 'new-event',
                'menu_id' => '4',
                'order' => '1',
                'access' => '3',
                'type' => '1',
                'parent_item_id' => '2',
                'url' => '',
                'route' => 'events.create',
                'font_awesome_class' => 'fa fas fa-plus-circle',
                'hide_name' => '0',
            ],
            ['id' => '4',
                'name' => 'My Events',
                'slug' => 'my-events',
                'menu_id' => '4',
                'order' => '2',
                'access' => '3',
                'type' => '1',
                'parent_item_id' => '2',
                'url' => '',
                'route' => 'events.index',
                'font_awesome_class' => 'far fa-calendar-alt',
                'hide_name' => '0',
            ],
            ['id' => '5',
                'name' => 'My Venues',
                'slug' => 'my-venues',
                'menu_id' => '4',
                'order' => '3',
                'access' => '3',
                'type' => '1',
                'parent_item_id' => '2',
                'url' => '',
                'route' => 'eventVenues.index',
                'font_awesome_class' => 'far fa-map-marker-alt',
                'hide_name' => '0',
            ],
            ['id' => '6',
                'name' => 'My Teachers',
                'slug' => 'my-teachers',
                'menu_id' => '4',
                'order' => '4',
                'access' => '3',
                'type' => '1',
                'parent_item_id' => '2',
                'url' => '',
                'route' => 'teachers.index',
                'font_awesome_class' => 'far fa-users',
                'hide_name' => '0',
            ],
            ['id' => '7',
                'name' => 'My Organizers',
                'slug' => 'my-organizers',
                'menu_id' => '4',
                'order' => '5',
                'access' => '3',
                'type' => '1',
                'parent_item_id' => '2',
                'url' => '',
                'route' => 'organizers.index',
                'font_awesome_class' => 'fas fa-users',
                'hide_name' => '0',
            ],
            ['id' => '8',
                'name' => 'Admin Tools',
                'slug' => 'admin-tools',
                'menu_id' => '4',
                'order' => '2',
                'access' => '4',
                'type' => '2',
                'parent_item_id' => '0',
                'url' => '#',
                'route' => '',
                'font_awesome_class' => 'far fa-cog',
                'hide_name' => '0',
            ],
            ['id' => '9',
                'name' => 'Users',
                'slug' => 'users',
                'menu_id' => '4',
                'order' => '1',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '8',
                'url' => '',
                'route' => 'users.index',
                'font_awesome_class' => 'fas fa-user-alt',
                'hide_name' => '0',
            ],
            ['id' => '10',
                'name' => 'Articles',
                'slug' => 'articles',
                'menu_id' => '4',
                'order' => '2',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '8',
                'url' => '',
                'route' => 'posts.index',
                'font_awesome_class' => 'far fa-file-alt',
                'hide_name' => '0',
            ],
            ['id' => '11',
                'name' => 'Events Categories',
                'slug' => 'events-categories',
                'menu_id' => '4',
                'order' => '4',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '8',
                'url' => '',
                'route' => 'eventCategories.index',
                'font_awesome_class' => 'fas fa-tags',
                'hide_name' => '0',
            ],
            ['id' => '12',
                'name' => 'Background Images',
                'slug' => 'background-images',
                'menu_id' => '4',
                'order' => '7',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '8',
                'url' => '',
                'route' => 'backgroundImages.index',
                'font_awesome_class' => 'far fa-images',
                'hide_name' => '0',
            ],
            ['id' => '13',
                'name' => 'Settings',
                'slug' => 'settings',
                'menu_id' => '4',
                'order' => '5',
                'access' => '5',
                'type' => '2',
                'parent_item_id' => '0',
                'url' => '#',
                'route' => '',
                'font_awesome_class' => 'fas fa-cog',
                'hide_name' => '1',
            ],
            ['id' => '14',
                'name' => 'Post Categories',
                'slug' => 'post-categories',
                'menu_id' => '4',
                'order' => '3',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '13',
                'url' => '',
                'route' => 'categories.index',
                'font_awesome_class' => 'far fa-tags',
                'hide_name' => '0',
            ],
            ['id' => '15',
                'name' => 'Menus',
                'slug' => 'menus',
                'menu_id' => '4',
                'order' => '8',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '13',
                'url' => '',
                'route' => 'menus.index',
                'font_awesome_class' => 'fas fa-caret-circle-down',
                'hide_name' => '0',
            ],
            ['id' => '16',
                'name' => 'Continents',
                'slug' => 'continents',
                'menu_id' => '4',
                'order' => '5',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '13',
                'url' => '',
                'route' => 'continents.index',
                'font_awesome_class' => 'fas fa-globe-americas',
                'hide_name' => '0',
            ],
            ['id' => '17',
                'name' => 'Countries',
                'slug' => 'countries',
                'menu_id' => '4',
                'order' => '6',
                'access' => '4',
                'type' => '1',
                'parent_item_id' => '13',
                'url' => '',
                'route' => 'countries.index',
                'font_awesome_class' => 'far fa-globe-americas',
                'hide_name' => '0',
            ],
            ['id' => '18',
                'name' => 'User tools',
                'slug' => 'user-tools',
                'menu_id' => '4',
                'order' => '6',
                'access' => '3',
                'type' => '2',
                'parent_item_id' => '0',
                'url' => '#',
                'route' => '',
                'font_awesome_class' => 'fas fa-user-circle',
                'hide_name' => '1',
            ],
            ['id' => '19',
                'name' => 'My Profile',
                'slug' => 'my-profile',
                'menu_id' => '4',
                'order' => '1',
                'access' => '3',
                'type' => '3',
                'parent_item_id' => '16',
                'url' => '',
                'route' => '',
                'font_awesome_class' => 'far fa-user-cog',
                'hide_name' => '1',
            ],
            ['id' => '20',
                'name' => 'Logout',
                'slug' => 'logout',
                'menu_id' => '4',
                'order' => '2',
                'access' => '3',
                'type' => '4',
                'parent_item_id' => '16',
                'url' => '',
                'route' => 'logout',
                'font_awesome_class' => 'fa fa-sign-out',
                'hide_name' => '1',
            ],
            ['id' => '21',
                'name' => 'Login',
                'slug' => 'login',
                'menu_id' => '4',
                'order' => '4',
                'access' => '2',
                'type' => '1',
                'parent_item_id' => '0',
                'url' => '',
                'route' => 'login',
                'font_awesome_class' => 'fa fa-sign-in',
                'hide_name' => '0',
            ],

        ];

        foreach ($menuItems as $key => $menuItem) {
            DB::table('menu_items')->insert([
                'id' => $menuItem['id'],
                'name' => $menuItem['name'],
                'slug' => $menuItem['slug'],
                'menu_id' => $menuItem['menu_id'],
                'order' => $menuItem['order'],
                'access' => $menuItem['access'],
                'type' => $menuItem['type'],
                'parent_item_id' => $menuItem['parent_item_id'],
                'url' => $menuItem['url'],
                'route' => $menuItem['route'],
                'font_awesome_class' => $menuItem['font_awesome_class'],
                'hide_name' => $menuItem['hide_name'],
            ]);
        }
    }
}
