filter:
    excluded_paths: 
        - "tests/"
        - "public/"
    
    dependency_paths:
        - "vendor/"

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

build:
    environment:
        php:
            version: 7.2
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
        unittests: 
            tests:
                override:
                  - command: './vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                    coverage:
                      file: build/logs/clover.xml   # <- Set this to where we find the coverage data.
                                                  #    The path is relative to the current directory.
                      format: php-clover
