language: php
php: 
    - 7.2
    - 7.3

addons:
  chrome: beta
  
before_script:
    - cp .env.travis .env
    - mysql -e 'create database testing;'
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan migrate --seed
#    - bundle exec chromedriver-update 73.0.3683.68
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - php artisan serve &

script:
    - vendor/bin/phpunit
    - php artisan dusk


# if the command fails for any reason it should retry it
# before executing our code execute a composer update so that the autoload is in place and make that Phpunit 
# is available
#before_script:
#    - travis_retry composer update

# the script we want to run
#script:
#    - vendor/bin/phpunit
