language: php
php: 
    - 7.2
    - 7.3

addons:
  chrome: stable
  
before_script:
    - cp .env.travis .env
    - mysql -e 'create database testing;'
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan migrate --seed

script:
    - vendor/bin/phpunit


# if the command fails for any reason it should retry it
# before executing our code execute a composer update so that the autoload is in place and make that Phpunit 
# is available
#before_script:
#    - travis_retry composer update

# the script we want to run
#script:
#    - vendor/bin/phpunit
