language: php
php: 
    - 7.2
    - 7.3
# if the command fails for any reason it should retry it
# before executing our code execute a composer update so that the autoload is in place and make that Phpunit 
# is available
before_script:
    - travis_retry composer update

# the script we want to run
script:
    - vendor/bin/phpunit
